permalink: /:categories/:title/
url: "http://pietrofontaz.github.io"
full_name: "Pietro Fontanesi"
first_name: "Shell In"
last_name: "A Forest"
blog_title: "Shells & Forests"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "P.F."
copyright_year: "2019"
google_analytics_code: ""
aboutme: "Music, photography, sometimes other kinds of art."
